---
- name: link dotfiles
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    # VIM Config Files
    - { src: "~/.dotfiles/vim/.vimrc", dest: "~/.vimrc" }
    - { src: "~/.dotfiles/vim/.vim", dest: "~/.vim" }
    # Git Config Files
    - { src: "~/.dotfiles/git/.gitconfig", dest: "~/.gitconfig" }
    # Link Bash Profile
    - { src: "~/.dotfiles/bash/.bash_profile", dest: "~/.bash_profile" }
    - { src: "~/.dotfiles/bash/.inputrc", dest: "~/.inputrc" }
    - { src: "~/.dotfiles/bash/.zshrc", dest: "~/.zshrc" }
