---
- name: link dotfiles
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    # VIM Config Files
    - { src: "~/.dotfiles/vim/.vimrc", dest: "~/.vimrc" }
    - { src: "~/.dotfiles/vim/.vim", dest: "~/.vim" }
