---
- name: link dotfiles
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    # VIM Config Files
    - { src: "~/.dotfiles/vim/.vimrc", dest: "~/.vimrc" }
    - { src: "~/.dotfiles/vim/.vim", dest: "~/.vim" }
    # VS Code
    - { src: "~/.dotfiles/config/vscode/settings.json", dest: "~/Library/Application Support/Code/User/settings.json" }
    - { src: "~/.dotfiles/config/vscode/keybindings.json", dest: "~/Library/Application Support/Code/User/keybindings.json" }
    # Git Config Files
    - { src: "~/.dotfiles/git/.gitconfig", dest: "~/.gitconfig" }
    # Link Bash Profile
    - { src: "~/.dotfiles/bash/.bash_profile", dest: "~/.bash_profile" }
    - { src: "~/.dotfiles/bash/.inputrc", dest: "~/.inputrc" }
    - { src: "~/.dotfiles/bash/.zshrc", dest: "~/.zshrc" }

    # Link Karabiner (custom mac keyboard)
    # - { src: "~/.dotfiles/config/karabiner/karabiner.json", dest: "~/.config/karabiner/karabiner.json" }
