---
- name: Include brew casks list
  include_vars: vars/casks.yml
  tags:
    - brew_cask

- block:
  - name: Update/upgrade homebrew
    homebrew: update_homebrew=yes upgrade_all=yes
    tags:
      - brew_cask

  - name: Manage Casks
    homebrew_cask: name={{ item.key }} state={{ item.value.state | default("present") }}
    with_dict: "{{casks}}"
    tags:
      - brew_cask

  when: ansible_os_family == "Darwin"
