---
- name: Playbook to manage justindra's dotfiles (https://github.com/justindra/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ./vars.yml
      tags: always

   # - name: Make sure dotfiles are present
   #   git: repo=git@github.com:justindra/dotfiles.git dest=~/.dotfiles

    - include: tasks/link_files.yml
      tags:
        - links

    - include: tasks/packages.yml
      tags:
        - packages

    - include: tasks/macos_defaults.yml
      when: ansible_os_family == "Darwin"
      tags:
        - macos_defaults

  handlers:
    - name: Kill Dock
      command: killall Dock
