---
- name: Playbook to manage justindra's dotfiles (https://github.com/justindra/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ./vars.yml
      tags: always

    - name: Make sure dotfiles are present
      git: repo=https://github.com/justindra/dotfiles.git dest=~/.dotfiles
